"""Interfaces for the wheel and arm drivers."""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable


@runtime_checkable
class ActuatorInterface(Protocol):
    """Methods every wheel driver must have."""

    def apply(self, command) -> None: ...
    def stop(self) -> None: ...
    def close(self) -> None: ...


@runtime_checkable
class ArmPlannerInterface(Protocol):
    """Methods every arm driver must have."""

    def goto(self, target, label: str = "") -> None: ...
    def open_gripper(self) -> None: ...
    def close_gripper(self) -> None: ...
    def collect(self, solved: list, tin_pose: str = "upright",
                dump: bool = True) -> bool: ...
    def dump_to_bin(self) -> None: ...
