colors:
  inner_left:
    lower:
    - 2
    - 255
    - 53
    upper:
    - 36
    - 255
    - 227
  inner_right:
    lower:
    - 37
    - 58
    - 0
    upper:
    - 179
    - 255
    - 53
  outer_left:
    lower:
    - 20
    - 125
    - 0
    upper:
    - 179
    - 255
    - 255
  outer_right:
    lower:
    - 0
    - 255
    - 67
    upper:
    - 3
    - 255
    - 255
