from dataclasses import dataclass
from typing import Optional, Dict

@dataclass
class ActionCommand:
    """Standardized action command generated by layers."""
    layer_id: int
    active: bool
    motion_vector: Optional[tuple] = None  # (v_x, v_y, v_theta)
    arm_action: Optional[str] = None       # e.g., 'deploy', 'retract', 'grab_arc'
    message: str = ""
    arm_params: Optional[Dict] = None      # payload for arm_action, e.g.
                                           # {'pose': [CH1..CH5]} for 'grab_arc'
                                           # {'target_m': (x, y)} for 'grab_ik'

class Arbitrator:
    """
    Subsumption Architecture Arbitrator.
    Higher priority layers (higher layer_id) suppress lower priority layers.
    """
    def __init__(self):
        # Dictionary to store the latest command from each layer
        self._current_votes: Dict[int, ActionCommand] = {}

    def submit_command(self, command: ActionCommand):
        """Layers submit their active commands here."""
        self._current_votes[command.layer_id] = command

    def get_winning_action(self) -> ActionCommand:
        """
        Evaluate all current layer votes and return the winning command.
        The highest layer_id that is active wins.
        """
        winning_cmd = ActionCommand(layer_id=-1, active=False, message="Idle")
        
        # Sort layers by priority (highest first)
        for layer_id in sorted(self._current_votes.keys(), reverse=True):
            cmd = self._current_votes[layer_id]
            if cmd.active:
                winning_cmd = cmd
                break  # Winner found, suppress all lower layers
                
        return winning_cmd

    def clear(self):
        """Clear votes for the next cycle."""
        self._current_votes.clear()
