from dataclasses import dataclass
from typing import Optional, Dict

@dataclass
class ActionCommand:
    """Standardized action command generated by layers."""
    layer_id: int
    active: bool
    motion_vector: Optional[tuple] = None  # (v_x, v_y, v_theta)
    arm_action: Optional[str] = None       # e.g., 'deploy', 'retract', 'grab_arc'
    message: str = ""
    arm_params: Optional[Dict] = None      # payload for arm_action, e.g.
                                           # {'pose': [CH1..CH5]} for 'grab_arc'

class Arbitrator:
    """Subsumption arbitrator: higher layer_id suppresses lower."""
    def __init__(self):
        # Latest command per layer.
        self._current_votes: Dict[int, ActionCommand] = {}

    def submit_command(self, command: ActionCommand):
        """Layers submit their active commands here."""
        self._current_votes[command.layer_id] = command

    def get_winning_action(self) -> ActionCommand:
        """Return the highest-priority active layer's command."""
        winning_cmd = ActionCommand(layer_id=-1, active=False, message="Idle")

        # Highest priority first.
        for layer_id in sorted(self._current_votes.keys(), reverse=True):
            cmd = self._current_votes[layer_id]
            if cmd.active:
                winning_cmd = cmd
                break

        return winning_cmd

    def clear(self):
        """Clear votes for the next cycle."""
        self._current_votes.clear()
