"""
Training Monitoring and Visualization
Tools for monitoring YOLOv8 training progress
"""

import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
import cv2
import numpy as np


def plot_training_results(results_csv_path):
    """
    Plot training metrics from results.csv
    
    Args:
        results_csv_path: Path to results.csv file generated by YOLOv8
    """
    
    # Read results
    df = pd.read_csv(results_csv_path)
    df.columns = df.columns.str.strip()  # Remove whitespace from column names
    
    # Create figure with subplots
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle('YOLOv8 Training Metrics', fontsize=16, fontweight='bold')
    
    # Plot 1: Loss curves
    ax = axes[0, 0]
    if 'train/box_loss' in df.columns:
        ax.plot(df['epoch'], df['train/box_loss'], label='Box Loss', linewidth=2)
    if 'train/cls_loss' in df.columns:
        ax.plot(df['epoch'], df['train/cls_loss'], label='Class Loss', linewidth=2)
    if 'train/dfl_loss' in df.columns:
        ax.plot(df['epoch'], df['train/dfl_loss'], label='DFL Loss', linewidth=2)
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.set_title('Training Losses')
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    # Plot 2: mAP scores
    ax = axes[0, 1]
    if 'metrics/mAP50(B)' in df.columns:
        ax.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@0.5', linewidth=2, color='green')
    if 'metrics/mAP50-95(B)' in df.columns:
        ax.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@0.5:0.95', linewidth=2, color='blue')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('mAP')
    ax.set_title('Mean Average Precision')
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_ylim([0, 1])
    
    # Plot 3: Precision and Recall
    ax = axes[0, 2]
    if 'metrics/precision(B)' in df.columns:
        ax.plot(df['epoch'], df['metrics/precision(B)'], label='Precision', linewidth=2, color='purple')
    if 'metrics/recall(B)' in df.columns:
        ax.plot(df['epoch'], df['metrics/recall(B)'], label='Recall', linewidth=2, color='orange')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Score')
    ax.set_title('Precision & Recall')
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_ylim([0, 1])
    
    # Plot 4: Learning Rate
    ax = axes[1, 0]
    if 'lr/pg0' in df.columns:
        ax.plot(df['epoch'], df['lr/pg0'], linewidth=2, color='red')
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Learning Rate')
    ax.set_title('Learning Rate Schedule')
    ax.grid(True, alpha=0.3)
    
    # Plot 5: Validation losses
    ax = axes[1, 1]
    if 'val/box_loss' in df.columns:
        ax.plot(df['epoch'], df['val/box_loss'], label='Val Box Loss', linewidth=2)
    if 'val/cls_loss' in df.columns:
        ax.plot(df['epoch'], df['val/cls_loss'], label='Val Class Loss', linewidth=2)
    if 'val/dfl_loss' in df.columns:
        ax.plot(df['epoch'], df['val/dfl_loss'], label='Val DFL Loss', linewidth=2)
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Loss')
    ax.set_title('Validation Losses')
    ax.legend()
    ax.grid(True, alpha=0.3)
    
    # Plot 6: Combined metrics
    ax = axes[1, 2]
    if 'metrics/mAP50(B)' in df.columns and 'metrics/precision(B)' in df.columns:
        ax.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@0.5', linewidth=2)
        ax.plot(df['epoch'], df['metrics/precision(B)'], label='Precision', linewidth=2)
        ax.plot(df['epoch'], df['metrics/recall(B)'], label='Recall', linewidth=2)
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Score')
    ax.set_title('Combined Metrics')
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_ylim([0, 1])
    
    plt.tight_layout()
    
    # Save plot
    output_path = Path(results_csv_path).parent / 'training_metrics.png'
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"✓ Training plots saved to: {output_path}")
    
    plt.show()


def visualize_predictions(image_path, results, save_path=None):
    """
    Visualize detection results on an image
    
    Args:
        image_path: Path to input image
        results: YOLO prediction results
        save_path: Path to save visualization (optional)
    """
    
    # Read image
    image = cv2.imread(str(image_path))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    # Draw predictions
    for result in results:
        boxes = result.boxes
        for box in boxes:
            # Get coordinates
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
            conf = box.conf[0].cpu().numpy()
            cls = int(box.cls[0].cpu().numpy())
            
            # Draw box
            cv2.rectangle(
                image,
                (int(x1), int(y1)),
                (int(x2), int(y2)),
                (0, 255, 0),
                2
            )
            
            # Draw label
            label = f'Can {conf:.2f}'
            cv2.putText(
                image,
                label,
                (int(x1), int(y1) - 10),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.5,
                (0, 255, 0),
                2
            )
    
    # Display
    plt.figure(figsize=(12, 8))
    plt.imshow(image)
    plt.axis('off')
    plt.title('Aluminum Can Detection Results')
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"✓ Visualization saved to: {save_path}")
    
    plt.show()


def summarize_training_run(run_dir):
    """
    Summarize a completed training run
    
    Args:
        run_dir: Directory containing training results
    """
    
    run_path = Path(run_dir)
    
    print("=" * 70)
    print(f"Training Run Summary: {run_path.name}")
    print("=" * 70)
    
    # Check for results.csv
    results_csv = run_path / 'results.csv'
    if results_csv.exists():
        df = pd.read_csv(results_csv)
        df.columns = df.columns.str.strip()
        
        print(f"\nTotal Epochs: {len(df)}")
        
        # Best metrics
        if 'metrics/mAP50(B)' in df.columns:
            best_map50 = df['metrics/mAP50(B)'].max()
            best_map50_epoch = df['metrics/mAP50(B)'].idxmax()
            print(f"Best mAP@0.5: {best_map50:.4f} (Epoch {best_map50_epoch})")
        
        if 'metrics/mAP50-95(B)' in df.columns:
            best_map = df['metrics/mAP50-95(B)'].max()
            best_map_epoch = df['metrics/mAP50-95(B)'].idxmax()
            print(f"Best mAP@0.5:0.95: {best_map:.4f} (Epoch {best_map_epoch})")
        
        # Final metrics
        print(f"\nFinal Metrics:")
        if 'metrics/precision(B)' in df.columns:
            print(f"  Precision: {df['metrics/precision(B)'].iloc[-1]:.4f}")
        if 'metrics/recall(B)' in df.columns:
            print(f"  Recall: {df['metrics/recall(B)'].iloc[-1]:.4f}")
    
    # Check for model weights
    weights_dir = run_path / 'weights'
    if weights_dir.exists():
        print(f"\nModel Weights:")
        if (weights_dir / 'best.pt').exists():
            print(f"  ✓ best.pt")
        if (weights_dir / 'last.pt').exists():
            print(f"  ✓ last.pt")
    
    print("=" * 70)


# Example usage
if __name__ == "__main__":
    # Example: Plot training results
    results_path = "runs/detect/yolov8s_aluminum_can/results.csv"
    
    if Path(results_path).exists():
        plot_training_results(results_path)
        
        # Summarize the run
        run_dir = Path(results_path).parent
        summarize_training_run(run_dir)
    else:
        print(f"Results file not found: {results_path}")
        print("Train the model first using train_yolov8.py")
